version: "3"

services:
  roouteplus:
    image: obaratch/react-express-sqlite-base
    build: .
    container_name: webapp
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 80:8080
      - 3000:3000
    volumes:
      - ./config:/home/node/config
      - ./log:/home/node/log
